- hosts: localhost
  vars:
   host: "192.168.1.1"
   username: "api"
   password: "api"
   vdom: "root"
   https: "False"
   ssl_verify: "False"
  tasks:
  - name: Configure IPv4 static routing tables.
    fortios_router_static:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: "False"
      state: "present"
      #state: "absent"
      router_static:
        dst: "123.123.123.123/32"
        gateway: "123.123.123.1"
        device: "wan2"
        seq_num: "100"
  - name : add a firewall policy
    fortios_firewall_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify: "False"
      state: "present"
      #state: "absent"
      firewall_policy:
        policyid: "100"
        name: "Created By Ansible"
        action: "accept"
        srcaddr:
          -
             name: "all"
        dstaddr:
          -
             name: "all"
        srcintf:
          -
             name: "wan2"
        dstintf:
          -
             name: "wan2"
        service:
          -
             name: "HTTP"
        schedule: "always"
        logtraffic: "all"
